DEFAULT_INTERNAL_EXTENSIONS: list[tuple[str, str]] = [
    ("Reception", "11"),
    ("Azizbek", "12"),
    ("Vazgen", "13"),
    ("Nail", "14"),
    ("Maksim", "15"),
    ("Shukhrat", "16"),
    ("Iroda", "17"),
    ("Madina", "18"),
    ("Anastasia", "19"),
    ("Aliye", "20"),
    ("Olga", "21"),
    ("Jahongir", "22"),
    ("Reception", "24"),
    ("Guzal", "25"),
    ("Alina M", "26"),
    ("Diyor", "27"),
    ("Kseniya", "29"),
    ("Ekaterina", "30"),
    ("Dilshodbek", "31"),
    ("Dilnoza", "32"),
    ("Islombek I", "33"),
    ("Islam Dj.", "34"),
    ("Shahzoda", "36"),
    ("Alina A", "37"),
    ("Amal", "46"),
    ("Tatyana", "47"),
    ("Kamila", "48"),
    ("Kumushkhon", "49"),
    ("Zafar", "50"),
    ("Sevara", "51"),
    ("Shahzodbek", "52"),
    ("Kamola", "53"),
]
